/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	arrivev1alpha1 "github.com/mattkelly/arrive/pkg/apis/arrive/v1alpha1"
	versioned "github.com/mattkelly/arrive/pkg/client/clientset/versioned"
	internalinterfaces "github.com/mattkelly/arrive/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/mattkelly/arrive/pkg/client/listers/arrive/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ArriveTestInformer provides access to a shared informer and lister for
// ArriveTests.
type ArriveTestInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ArriveTestLister
}

type arriveTestInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewArriveTestInformer constructs a new informer for ArriveTest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewArriveTestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredArriveTestInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredArriveTestInformer constructs a new informer for ArriveTest type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredArriveTestInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArriveV1alpha1().ArriveTests(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ArriveV1alpha1().ArriveTests(namespace).Watch(options)
			},
		},
		&arrivev1alpha1.ArriveTest{},
		resyncPeriod,
		indexers,
	)
}

func (f *arriveTestInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredArriveTestInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *arriveTestInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&arrivev1alpha1.ArriveTest{}, f.defaultInformer)
}

func (f *arriveTestInformer) Lister() v1alpha1.ArriveTestLister {
	return v1alpha1.NewArriveTestLister(f.Informer().GetIndexer())
}
