/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/mattkelly/arrive/pkg/apis/arrive/v1alpha1"
	scheme "github.com/mattkelly/arrive/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ArriveTestsGetter has a method to return a ArriveTestInterface.
// A group's client should implement this interface.
type ArriveTestsGetter interface {
	ArriveTests(namespace string) ArriveTestInterface
}

// ArriveTestInterface has methods to work with ArriveTest resources.
type ArriveTestInterface interface {
	Create(*v1alpha1.ArriveTest) (*v1alpha1.ArriveTest, error)
	Update(*v1alpha1.ArriveTest) (*v1alpha1.ArriveTest, error)
	UpdateStatus(*v1alpha1.ArriveTest) (*v1alpha1.ArriveTest, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ArriveTest, error)
	List(opts v1.ListOptions) (*v1alpha1.ArriveTestList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ArriveTest, err error)
	ArriveTestExpansion
}

// arriveTests implements ArriveTestInterface
type arriveTests struct {
	client rest.Interface
	ns     string
}

// newArriveTests returns a ArriveTests
func newArriveTests(c *ArriveV1alpha1Client, namespace string) *arriveTests {
	return &arriveTests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the arriveTest, and returns the corresponding arriveTest object, and an error if there is any.
func (c *arriveTests) Get(name string, options v1.GetOptions) (result *v1alpha1.ArriveTest, err error) {
	result = &v1alpha1.ArriveTest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("arrivetests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ArriveTests that match those selectors.
func (c *arriveTests) List(opts v1.ListOptions) (result *v1alpha1.ArriveTestList, err error) {
	result = &v1alpha1.ArriveTestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("arrivetests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested arriveTests.
func (c *arriveTests) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("arrivetests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a arriveTest and creates it.  Returns the server's representation of the arriveTest, and an error, if there is any.
func (c *arriveTests) Create(arriveTest *v1alpha1.ArriveTest) (result *v1alpha1.ArriveTest, err error) {
	result = &v1alpha1.ArriveTest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("arrivetests").
		Body(arriveTest).
		Do().
		Into(result)
	return
}

// Update takes the representation of a arriveTest and updates it. Returns the server's representation of the arriveTest, and an error, if there is any.
func (c *arriveTests) Update(arriveTest *v1alpha1.ArriveTest) (result *v1alpha1.ArriveTest, err error) {
	result = &v1alpha1.ArriveTest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("arrivetests").
		Name(arriveTest.Name).
		Body(arriveTest).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *arriveTests) UpdateStatus(arriveTest *v1alpha1.ArriveTest) (result *v1alpha1.ArriveTest, err error) {
	result = &v1alpha1.ArriveTest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("arrivetests").
		Name(arriveTest.Name).
		SubResource("status").
		Body(arriveTest).
		Do().
		Into(result)
	return
}

// Delete takes name of the arriveTest and deletes it. Returns an error if one occurs.
func (c *arriveTests) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("arrivetests").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *arriveTests) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("arrivetests").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched arriveTest.
func (c *arriveTests) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ArriveTest, err error) {
	result = &v1alpha1.ArriveTest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("arrivetests").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
